### ISSUE TITLE
UI support for private DAOs

### ISSUE THREAD

**Issue by Ashe-Oro** [hashgraph/hedera-accelerator-defi-dex-ui#343]
### Problem

Currently, private DAOs are not supported by the HashioDAO UI. This prevents me from creating and testing in private. 

### Solution

Add support for private DAOs on the UI so I can manage then the same as with public DAOs.

**Comment by PFC-developer** [comment]
this was completed in PR #358

**Comment by web3-nomad** [comment]
PR #358
